networks:
  app-network:
    driver: bridge

services:
  # Node.js / Express backend
  backend:
    build:
      context: .
      dockerfile: infra/docker/node.Dockerfile
    command: npm run dev
    restart: always
    volumes:
      - ./services/backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  webapp1:
    build:
      context: .
      dockerfile: infra/docker/react-display.Dockerfile
    restart: always
    volumes:
      - ./apps/webapp1_realtime_data:/app
      - webapp1_node_modules:/app/node_modules
    ports:
      - "3001:5173"
    depends_on:
      - backend
    networks:
      - app-network

  # React frontend #2 (device management)

volumes:
  webapp1_node_modules:
