networks:
  app-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.net.preferIPv4Stack=true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "medical-device-data:1:1"
    ports:
      - "9092:9092"  
    depends_on:
      - zookeeper
    networks:
      - app-network

  telegraf:
    image: telegraf:1.28
    restart: always
    environment:
      - KAFKA_BROKER=kafka:9092
      - INFLUXDB_HOST=influxdb:8086
    volumes:
      - /home/user/telegraf/telegraph.conf:/etc/telegraf/telegraph.conf:ro
    depends_on:
      - kafka
      - influxdb
    networks:
      - app-network

  # Obstoječi InfluxDB na strežniku
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - app-network
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

volumes:
  influxdb-data:
  influxdb-config:

