name: CI - Main

on:
  push:
    branches:
      - development
      - frontend_popravki2
 
env:
  REGISTRY: docker.io
  DOCKERHUB_REPO: rokfonovic
 
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push Node.js backend
        run: |
          docker build \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg INFLUX_URL=${{ secrets.INFLUX_URL }} \
            --build-arg INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }} \
            --build-arg INFLUX_ORG=${{ secrets.INFLUX_ORG }} \
            -t $REGISTRY/$DOCKERHUB_REPO/node-backend:latest \
            -f infra/docker/node.Dockerfile \
            .
          docker push $REGISTRY/$DOCKERHUB_REPO/node-backend:latest