# .github/workflows/ci-dev.yml
name: CI - Development

on:
  push:
    branches:
      - development

env:
  REGISTRY: docker.io
  DOCKERHUB_REPO: rokfonovic

jobs:
  build-fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Gradnja in potiskanje FastAPI (consumer) slike
      - name: Build and push FastAPI consumer
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/fastapi.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/fastapi:latest

  build-frontend1:
    runs-on: ubuntu-latest
    needs: build-fastapi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env.production
        run: |
          cat <<EOF > apps/webapp1_realtime_data/.env.production
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          EOF

      # Gradnja in potiskanje frontend1 (React - realtime data) slike
      - name: Build and push frontend1
        uses: docker/build-push-action@v3
        with:
          context: ./apps/webapp1_realtime_data
          file: infra/docker/react-display.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend1-data:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
  build-frontend2:
    runs-on: ubuntu-latest
    needs: build-frontend1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env.production
        run: |
          cat <<EOF > apps/webapp2_med_devices/.env.production
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          EOF

      # Gradnja in potiskanje frontend2 (React - device management) slike
      - name: Build and push frontend2
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/react-admin.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend2-admin:latest
