name: CI - Main

on:
  push:
    branches:
      - development
      - frontend_popravki2
 
env:

  REGISTRY: docker.io

  DOCKERHUB_REPO: rokfonovic
 
jobs:

  build-backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push Node.js backend

        run: |

          docker build \

            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \

            -t $REGISTRY/$DOCKERHUB_REPO/node-backend:latest \

            -f infra/docker/node.Dockerfile \

            .

          docker push $REGISTRY/$DOCKERHUB_REPO/node-backend:latest

 
  build-frontend1:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push frontend1

        uses: docker/build-push-action@v3

        with:

          context: .

          file: infra/docker/react-display.Dockerfile

          push: true

          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend1-data:latest

          build-args: |

            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

  build-frontend2:

    runs-on: ubuntu-latest

    needs: build-frontend1

    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push frontend1

        uses: docker/build-push-action@v3

        with:

          context: .

          file: infra/docker/react-admin.Dockerfile

          push: true

          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend2-admin:latest

          build-args: |

            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

 