name: CI - Main

on:
  push:
    branches:
      - development

env:
  REGISTRY: docker.io
  DOCKERHUB_REPO: rokfonovic

jobs:
  build-frontend1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend1
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/react-display.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend1-data:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
