name: CI - Main

on:
  push:
    branches:
      - development

env:
  REGISTRY: docker.io
  DOCKERHUB_REPO: rokfonovic

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [capnograph]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Gradnja in potiskanje provider slik za vsako napravo
      - name: Build and push provider image ${{ matrix.device }}
        run: |
          docker build \
            --build-arg DEVICE_NAME=${{ matrix.device }} \
             -t ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/provider_${{ matrix.device }}:latest \
            -f infra/docker/python-provider.Dockerfile \
            .
          docker push ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/provider_${{ matrix.device }}:latest
 
