name: CI - Main

on:
  push:
    branches:
      - development

env:
  REGISTRY: docker.io
  DOCKERHUB_REPO: rokfonovic

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [capnograph, ecg, infusion, ventilator, nibp, spo2, temperature]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Gradnja in potiskanje provider slik za vsako napravo
      - name: Build and push provider image ${{ matrix.device }}
        run: |
          docker build \
            --build-arg DEVICE_NAME=${{ matrix.device }} \
             -t ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/provider_${{ matrix.device }}:latest \
            -f infra/docker/python-provider.Dockerfile \
            .
          docker push ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/provider_${{ matrix.device }}:latest
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Node.js backend
        run: |
          docker build \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg INFLUX_URL=${{ secrets.INFLUX_URL }} \
            --build-arg INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }} \
            --build-arg INFLUX_ORG=${{ secrets.INFLUX_ORG }} \
            -t $REGISTRY/$DOCKERHUB_REPO/node-backend:latest \
            -f infra/docker/node.Dockerfile \
            .
          docker push $REGISTRY/$DOCKERHUB_REPO/node-backend:latest

  build-fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FastAPI consumer
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/fastapi.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/fastapi:latest

  build-frontend1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend1
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/react-display.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend1-data:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
  build-frontend2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend1
        uses: docker/build-push-action@v3
        with:
          context: .
          file: infra/docker/react-admin.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}/frontend2-admin:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
