# .github/workflows/deploy-prod.yml
name: CD - Production Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy all services on Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/providers-deployments.yaml
          kubectl apply -f k8s/frontend1-deployment.yaml
          kubectl apply -f k8s/frontend2-deployment.yaml
          kubectl apply -f k8s/kafka-deployment.yaml
          kubectl apply -f k8s/zookeeper-deployment.yaml
          kubectl apply -f k8s/telegraf-deployment.yaml
