name: Manual Merge development → test

on:
  workflow_dispatch:
  push:
    branches:
      - development
jobs:
  merge-dev-to-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout test branch
        run: git checkout test

      - name: Merge development into test, preferring development (theirs)
        run: |
          git merge origin/development --strategy-option theirs --no-edit || echo "No changes to merge"

      - name: Push changes to test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin test
